name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run database migrations
      run: |
        export FLASK_APP=app.py 
        flask db upgrade

    - name: Start Flask Server
      run: |
        export FLASK_APP=app.py
        flask run &
      shell: bash

    - name: Wait for Flask server to start
      run: sleep 5
  
    - name: Run component tests
      run: |
        behave tests_component/ ||true

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage xml
        coverage report

    - name: Run mutation tests
      run: mutmut run --paths-to-mutate=./LIVRE/ --tests-dir=./TEST/ --runner="pytest" || true

    - name: Show mutation test results
      run: mutmut results

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
