- name: Set PYTHONPATH
  run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

name: TDD_YNOV

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: pytest ./TEST

    # Ajoutez ici d'autres étapes si nécessaire, comme la publication des résultats des tests
