name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mutmut

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage xml
        coverage report

        
    - name: Run mutation tests
      run : mutmut run --paths-to-mutate=./LIVRE/ --tests-dir=TDD_YNOV/TEST/ --runner="pytest"

    - name: Show mutation test results
      run: mutmut results
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
